apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: website-ingress
spec:
  tls:
    - hosts:
        - new.mindspore.cn
      secretName: website-tls
  rules:
    - host: new.mindspore.cn
      http:
        paths:
          - backend:
              serviceName: websiteservice
              servicePort: 80
            path: /
