#- purge-cache.yaml
#- purge-secrets.yaml
resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
- secrets.yaml
- job.yaml
- oauth-proxy.yaml
- cibot-service.yaml
- www-ingress.yaml
namespace: website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-website
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-website
  newTag: c311e7edc4a4e4097f71c58576816edc80b25190
