#- purge-cache.yaml
#- purge-secrets.yaml
resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
- secrets.yaml
- job.yaml
- oauth-proxy.yaml
- cibot-service.yaml
namespace: website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-website
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-website
  newTag: a5bc9ca7e729a5ba29a9c1e36a2760d9b5e1b4bd
