---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: website-secrets
spec:
  name: website-secrets
  keysMap:
    mail_password:
      path: secrets/data/mindspore/website-secrets
      key: mail_password
    mysql_password:
      path: secrets/data/mindspore/website-secrets
      key: mysql_password
    pytorch_url:
      path: secrets/data/mindspore/website-secrets
      key: pytorch_url
    redis_password:
      path: secrets/data/mindspore/website-secrets
      key: redis_password
