---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.mindspore.cn
  name: mindspore-www-website-ingress
spec:
  tls:
    - hosts:
        - mindspore.cn
      secretName: website-tls
  rules:
    - host: mindspore.cn
      http:
        paths:
          - backend:
              serviceName: websiteservice
              servicePort: 80
            path: /
