---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/custom-http-errors: '400,500,404'
    nginx.ingress.kubernetes.io/server-snippet: |
      rewrite ^~/ https://www.mindspore.cn redirect;
      rewrite ^~/resource(.*) https://gitee.com/mindspore/book redirect;
  name: mindspore-www-website-ingress
spec:
  tls:
    - hosts:
        - mindspore.cn
      secretName: website-tls-2
  rules:
    - host: mindspore.cn
      http:
        paths:
          - backend:
              serviceName: websiteservice
              servicePort: 80
            path: /
