---
kind: Service
apiVersion: v1
metadata:
  name: mindspore-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mindspore-frontend
---
kind: Service
apiVersion: v1
metadata:
  name: bless-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: bless-server
