---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mindspore-jenkins
spec:
  name: mindspore-jenkins
  keysMap:
    jenkins-admin-user:
      path: secrets/data/mindspore/jenkins_secrets
      key: jenkins-admin-user
    jenkins-admin-password:
      path: secrets/data/mindspore/jenkins_secrets
      key: jenkins-admin-password
    jenkins-user-password:
      path: secrets/data/mindspore/jenkins_secrets
      key: jenkins-user-password
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mindspore-jenkins-tls
spec:
  name: mindspore-jenkins-tls
  keysMap:
    ca.crt:
      path: secrets/data/mindspore/website-secrets
      key: server.crt
    tls.crt:
      path: secrets/data/mindspore/website-secrets
      key: server.crt
    tls.key:
      path: secrets/data/mindspore/website-secrets
      key: server.key
