resources:
  - https://github.com/opensourceways/app-meetingbot/deploy?ref=stable
  - secrets.yaml
  - ingress.yaml
  - namespace.yaml
commonLabels:
  app: mindspore-meetingbot
patchesStrategicMerge:
  - configmap.yaml
  - deployment.yaml
patchesJson6902:
  - target:
      group: "apps"
      version: v1
      kind: Deployment
      name: meet-bot
    path: patch-env.yaml
namespace: meeting
