---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mindspore-data-volume-new
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  storageClassName: ssd
