---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: rsync-secrets
spec:
  name: rsync-secrets
  keysMap:
    rsyncd_secrets:
      path: secrets/data/mindspore/rsync
      key: rsyncd_secrets
    auth_files:
      path: secrets/data/mindspore/repo
      key: auth_files

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: download-secrets
spec:
  name: download-secrets
  keysMap:
    ca.crt:
      path: secrets/data/mindspore/website-secrets
      key: server.crt
    tls.crt:
      path: secrets/data/mindspore/website-secrets
      key: server.crt
    tls.key:
      path: secrets/data/mindspore/website-secrets
      key: server.key

