apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: rsync-secrets
spec:
  name: rsync-secrets
  keysMap:
    rsyncd_secrets:
      path: secrets/data/mindspore/rsync
      key: rsyncd_secrets
    server.crt:
      path: secrets/data/mindspore/website
      key: server.crt
    server.key:
      path: secrets/data/mindspore/website
      key: server.key
