resources:
  - ingress.yaml
  - namespace.yaml
  - nginx-purge.yaml
  - poetry-service.yaml
commonLabels:
  app: mindspore-api
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: poetry-service
    path: selector.yaml
namespace: mindspore-api
