resources:
  - https://github.com/opensourceways/app-repo/deploy?ref=stable
  - pvc.yaml
  - namespace.yaml
  - secrets.yaml
  - ingress.yaml
commonLabels:
  app: mindspore-cn-north4-download-repo
patchesStrategicMerge:
  - configmap.yaml
  - deployment.yaml
namespace: download


