---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mindspore-data-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5000Gi
  storageClassName: ssd