apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: website-secrets
  namespace: repo
spec:
  name: website-secrets
  keysMap:
    rsyncd_secrets:
      path: secrets/data/mindspore/repo
      key: rsyncd.secrets
    auth_files:
      path: secrets/data/mindspore/repo
      key: auth_files

